MODULES = [
    {
        "id": "brainhole",
        "name": "灵犀脑洞",
        "category": "创作",
        "tagline": "把普通东西变成 5 个离谱但可落地的创意场景。",
        "actions": ["五连脑洞", "故事展开", "产品概念"],
    },
    {
        "id": "companion",
        "name": "灵伴",
        "category": "陪伴",
        "tagline": "24 小时情感陪伴，懂你也陪你复盘。",
        "actions": ["温柔陪聊", "心情总结", "疗愈建议"],
    },
    {
        "id": "avatar",
        "name": "分身",
        "category": "陪伴",
        "tagline": "基于你提供的样本，生成更像你语气的回复。",
        "actions": ["风格样本", "代回消息", "朋友圈文案"],
    },
    {
        "id": "treehole",
        "name": "树洞",
        "category": "陪伴",
        "tagline": "匿名倾诉、情绪命名、生成焚烧仪式文案。",
        "actions": ["匿名倾诉", "情绪天气", "焚烧文案"],
    },
    {
        "id": "writing",
        "name": "妙笔",
        "category": "创作",
        "tagline": "小红书、朋友圈、周报、邮件一键起稿。",
        "actions": ["闪写", "改写润色", "生成标签"],
    },
    {
        "id": "office_doc",
        "name": "快文",
        "category": "创作",
        "tagline": "会议纪要、正式邮件、PPT 大纲的职场写作台。",
        "actions": ["会议纪要", "商务邮件", "PPT 大纲"],
    },
    {
        "id": "image_fix",
        "name": "秒修",
        "category": "影像",
        "tagline": "上传图片后调用真实图像编辑，生成修图结果和参数建议。",
        "actions": ["一键美化", "风格建议", "证件照参数"],
    },
    {
        "id": "dressup",
        "name": "换装",
        "category": "影像",
        "tagline": "上传人像后调用真实图像编辑，生成换装图和 OOTD 文案。",
        "actions": ["职业装", "旅行装", "约会装"],
    },
    {
        "id": "study",
        "name": "解题侠",
        "category": "学习",
        "tagline": "拍题后分步讲解，不只给答案。",
        "actions": ["拍照解题", "作文批改", "错题本"],
    },
    {
        "id": "knowledge",
        "name": "知了",
        "category": "学习",
        "tagline": "任意知识秒懂，并生成可分享知识卡片。",
        "actions": ["知识问答", "每日卡片", "闯关题"],
    },
    {
        "id": "resume",
        "name": "职达",
        "category": "求职",
        "tagline": "简历评分、JD 匹配、模拟面试一站完成。",
        "actions": ["简历评分", "JD 优化", "模拟面试"],
    },
    {
        "id": "career",
        "name": "职画",
        "category": "求职",
        "tagline": "测评职业方向，生成 30/60/90 天行动计划。",
        "actions": ["职业测试", "路径规划", "技能差距"],
    },
    {
        "id": "car_radio",
        "name": "灵犀电台",
        "category": "陪伴",
        "tagline": "上车一句话，私人 AI 音频陪你通勤。",
        "actions": ["通勤播报", "情绪陪伴", "英语听力", "脑洞故事"],
    },
]

MODULE_BY_ID = {item["id"]: item for item in MODULES}
